### ISSUE TITLE
Error during Initialize plugin : QuartzScheduler-backup already exists

### ISSUE THREAD

**Issue by lilian-benoit** [jyuch/gitbucket-backup-plugin#1]
I use gitbucket 4.27 on Linux

I have a error when i want add gitbucket-backup-plugin : **Scheduler with name 'QuartzScheduler~backup' already exists.**

> 20:54:47.338 [Thread-148] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-backup-plugin-gitbucket_4.27.
> 20:54:47.540 [Thread-148] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.
>20:54:47.542 [Thread-148] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.
> 20:54:47.543 [Thread-148] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
> 20:54:47.545 [Thread-148] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'QuartzS
>   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
>   NOT STARTED.
>   Currently in standby mode.
>   Number of jobs executed: 0
>   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
>   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
> 20:54:47.547 [Thread-148] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler QuartzScheduler backup
> 20:54:47.549 [Thread-148] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.3
> 20:54:47.552 [Thread-148] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-back
> java.lang.ExceptionInInitializerError: null
>         at io.github.gitbucket.backup.service.ActorService.initialize(ActorService.scala:15)
>         at io.github.gitbucket.backup.service.ActorService.initialize$(ActorService.scala:14)
>         at Plugin.initialize(Plugin.scala:9)
>         at Plugin.initialize(Plugin.scala:19)
>         at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:355)
>         at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:317)
>         at scala.collection.immutable.List.foreach(List.scala:389)
>         at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:317)
>         at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistry.scala:217)
>         at gitbucket.core.plugin.PluginWatchThread$$anon$1.$anonfun$run$3(PluginRegistry.scala:476)
>         at gitbucket.core.plugin.PluginWatchThread$$anon$1.$anonfun$run$3$adapted(PluginRegistry.scala:474)
>         at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(
>         at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
>         at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(
>         at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile
>         at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingPro
>         at gitbucket.core.plugin.PluginWatchThread$$anon$1.run(PluginRegistry.scala:474)
> Caused by: org.quartz.SchedulerException: **Scheduler with name 'QuartzScheduler~backup' already exists.**
>         at org.quartz.impl.SchedulerRepository.bind(SchedulerRepository.java:80)
>         at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:529)
>         at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:415)
>         at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:372)
>         at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:330)
>         at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:298)

**Comment by jyuch** [comment]
I was unable to reproduce the problem. (Debian stretch, openjdk8, standalone app)
Can you provide little more information ?

- GitBucket deployment mode (standalone app, under webcontainer)
- JRE vendor and version
- Other installed plugins
- Content of `backup.conf`

**Comment by lilian-benoit** [comment]
Backup plugin isn't visible on plugins page.

Environment :
- Gitbucket under webcontainer (OpenLiberty 17.0.0.4 [servlet 3.1])
- Oracle JDK 8u162 
- List of installed plugins
  - gitbucket-backup-plugin-gitbucket_4.27.0-1.0.0.jar
  - gitbucket-gist-plugin-gitbucket_4.25.0-4.15.0.jar
  - gitbucket-mirror-plugin-assembly-1.0.2.jar
  - gitbucket-monitorting-plugin_2.12-3.1.0.jar
  - gitbucket-network-plugin_2.12-1.6.1.jar
  - gitbucket-notifications-plugin-gitbucket_4.27.0-1.6.0.jar
  - gitbucket-pages-plugin_2.12-1.7.1.jar
- Content of `backup.conf`
```
# Backup timing (Required)
# For details, see http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html
# This example, backup 12am every day
akka {
  quartz {
    schedules {
      Backup {
        expression = "0 0 0 * * ?"
      }
   }
  }
}

backup {
  # Backup archive destination directory (Optional)
  # If not specified, archive is saved into GITBUCKET_HOME
  archive-destination = """/opt/sauvegarde/gitmgr/plugins"""

  # Maximum number of backup archives to keep (if 0 or negative value, keep unlimited) (Optional)
  # If not specified, keep unlimited
  archive-limit = 10

  # Send notify email when backup is success (Optional, default:false)
  notify-on-success = true

  # Send notify email when backup is failure (Optional, default:false)
  notify-on-failure = true

  # Notify email destination (Optional)
  notify-dest = ["my-mail@me.org"]

  # S3 compatible object storage for backup upload (Optional)
  #s3 {
  #  # Endpoing URL
  #  endpoint = "http://localhost:9000"

  #  # Region
  #  region = "US_EAST_1"

  #  # Access key
  #  access-key = "access-key"

  #  # Secret key
  #  secret-key = "secret-key"

  #  # Bucket of backup destination
  #  bucket = "gitbucket"
  #}
}
```

**Comment by lilian-benoit** [comment]
I use external db : postgresql.
I don't found a table for quartz schedule ? it's not persistent ?

I had seen that property 'archive-destination' have three quotation mark on my `backup.conf` file (like readme.md). I changed for one quotation mark. I restart and i had not no error.

I try to using three quotation mark. I restart and i had not no error

Now, I don't reproduce my problem. I propose to close this issue.
Thanks for your time
