### ISSUE TITLE
バックアップ失敗

### ISSUE THREAD

**Issue by thisis-epopa** [jyuch/gitbucket-backup-plugin#11]
#2 と関連かもしれませんが、エラーは出てませんが、最終的なzipファイル(#2をみると)が生成されません。

環境としては、次の通りです。
gitubucket 4.33.0
gitbucket-backup-plugin 1.2.2
リポジトリサイズ　100GB

タイムアウトになっている可能性があると思うので、タイムアウトの時間を長く設定していただけないでしょうか。
お時間のある際に、対応していただけたら幸いです。

**Comment by jyuch** [comment]
そのリポジトリサイズだとご指摘の通りタイムアウトが原因となっている可能性が非常に高いです。
ただ、念のため状況を確認したいので可能であればセンシティブな情報をマスクしたうえでログを頂くことは可能でしょうか。

また、リポジトリサイズの傾向はどのようになっていますか。（100GB×1なのか、1GB×100なのか）
こちらもざっくりとした傾向で良いので教えてください。

**Comment by thisis-epopa** [comment]
社内運用のため、ログを直接お見せすることは出来ませんが、バックアップするリポジトリを(A～Z)と仮定した場合、以下のようなログが出ています。

バックアップ開始時刻: 23:30 
[INFO] [11/10/2021 23:30.359] [backup-akka.actor.default-dispatcher-5] [akka://backup/user/backup/cloner] Clone repository A
[INFO] [11/10/2021 23:33.359] [backup-akka.actor.default-dispatcher-5] [akka://backup/user/backup/cloner] Clone repository B
・・・
[INFO] [11/07/2021 23:55.359] [backup-akka.actor.default-dispatcher-5] [akka://backup/user/backup/cloner] Clone repository Z

`リポジトリのサイズは、ざっくりと次のような感じです。`
40GB × 1
20GB × 2
5GB × 3
0~1GB × 10

**Comment by jyuch** [comment]
決め打ちだったタイムアウト値を設定ファイルで指定できるように改修しました。

ただ、リポジトリのサイズが非常に大きいためタイムアウト値を調整してもそれ以外の部分（ZIP圧縮や古いアーカイブのクリーンアップ処理など）で問題が出るかもしれません。
その場合は別に手段でのバックアップの検討をお願いするかもしれません。
