### ISSUE TITLE
バックアップの失敗

### ISSUE THREAD

**Issue by Ry0** [jyuch/gitbucket-backup-plugin#2]
一日おきにバックアップするよう設定を行い運用していますが、バックアップに失敗するときと成功するときがあります。
失敗した時は、バックアップの作業フォルダは生成されるものの、zipが生成されません。
実行時のログを見ただけでは原因がわからず、issueで質問させていただきました。

ログをみると下記のようなメッセージが出て次の処理を行うことなく終了しています。
```bash
[INFO] [11/07/2018 23:05:56.359] [backup-akka.actor.default-dispatcher-30] [akka://backup/user/backup/cloner] Clone repository ry0/test
[INFO] [11/07/2018 23:05:56.359] [backup-akka.actor.default-dispatcher-30] [akka://backup/deadLetters] Message [scala.runtime.BoxedUnit] from Actor[akka://backup/user/backup/cloner#1671833524] to Actor[akka://backup/deadLetters] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'
```

正常に動作した場合は、バックアップの数を一定に保つ処理が走っています。

```bash
[INFO] [11/06/2018 23:04:42.932] [backup-akka.actor.default-dispatcher-20] [akka://backup/user/backup/cloner] Clone repository ry0/test
[INFO] [11/06/2018 23:08:05.237] [backup-akka.actor.default-dispatcher-20] [akka://backup/user/backup/packer] Delete archive C:\gitbucket\resources\backup\backup-201811032300.zip
[INFO] [11/06/2018 23:08:05.346] [backup-akka.actor.default-dispatcher-20] [akka://backup/user/backup/packer] Delete archive C:\gitbucket\resources\backup\backup-201811012300.zip
[INFO] [11/06/2018 23:08:06.438] [backup-akka.actor.default-dispatcher-20] [akka://backup/user/backup/packer] Backup complete.
```
何かこの情報からわかることがありましたら、ご返信ください。

**Comment by jyuch** [comment]
もしかしたらリポジトリの総数が多い（リポジトリのサイズが大きい）ためにクローン処理の最中に処理がタイムアウトしているかもしれません。
各ステップのタイムアウト間隔を延長した（5分→30分）ビルドを添付したので試してみてください。

[gitbucket-backup-plugin-gitbucket_4.29.0-1.2.1-SNAPSHOT.zip](https://github.com/jyuch/gitbucket-backup-plugin/files/2561878/gitbucket-backup-plugin-gitbucket_4.29.0-1.2.1-SNAPSHOT.zip)

また、リポジトリ総数・合計バイト数（`GITBUCKET_HOME/repositories`のサイズ）も教えていただけますでしょうか。

**Comment by Ry0** [comment]
ご対応ありがとうございます。
対策用のビルド済みファイルまで作成いただき感謝いたします。
repositoriesのサイズが4.20 GB (4,516,426,886 バイト)で非常に大きいので，タイムアウトしている可能性が非常に高いです。
Gitbucketを動作させているCPUがCeleronでバックアップ先のストレージもHDDであることも実行時間をさらに遅くしていると思います。

頂いたjarも含めてこちらで動作検証させていただきます。
変更いただいた時間というのは下記の箇所であっていますか？

`BackupActor.scala`

```diff
override def receive: Receive = {
  case DoBackup() => {
    val backupName = Directory.getBackupName

    val tempBackupDir = new File(gDirectory.GitBucketHome, backupName)
    - implicit val timeout: Timeout = Timeout(5 minutes)
    + implicit val timeout: Timeout = Timeout(30 minutes)
```

**Comment by jyuch** [comment]
はい、あっています。
詳しくはPR #3 の内容を確認してください。
