### ISSUE TITLE
The cron job seems to calculate TimeZone effect?

### ISSUE THREAD

**Issue by LowDensity** [jyuch/gitbucket-backup-plugin#8]
I had my cron expression set to :
`  expression = "0 0 0 1/16 * ?"` 
which according to CronMaker.com , sets this to automatically launch
on midnigiht(00:00) every half month(1/17th day).
But instead it happened in 0800(according to folder name).
plus ,  The server lives in UTC+0800.

**Comment by jyuch** [comment]
By default, the time is interpreted as UTC.
And you can specify timezone explicit.

e.g.
```
akka {
  quartz {
    schedules {
      Backup {
        expression = "0 0 0 * * ?"
        timezone = "Asia/Tokyo"
      }
    }
  }
}
```

**Comment by LowDensity** [comment]
thanks , it might take some time to check this out. I will let you know if it worked out.

**Comment by LowDensity** [comment]
It worked out well , thanks.
